secretKey: "a30422ec-d90b-44a0-bf48-287d15b4faeb"
dev: true
host: "0.0.0.0"
port: 8080
projectName: "pets_tracker"
database:
    name: "pets_tarcker_mvp"
    user: "main_user"
    password: "GgNPDviStW3JMAQ"
    domain: ds263146.mlab.com
    port: 63146
smtp:
    host: 'smtp.gmail.com'
    port: '465'
    secure: true
    auth:
        user: 'fabricio.ballon@ucsp.edu.pe'
        pass: ''
