secretKey: "a30422ec-d90b-44a0-bf48-287d15b4faeb"
dev: true
host: "0.0.0.0"
port: 8000
projectName: "project_name"
database:
    name: "db_name"
    user: "db_user"
    password: "db_pass"
    domain: db_host
    port: db_port
smtp:
    host: 'smtp.gmail.com'
    port: '465'
    secure: true
    auth:
        user: ''
        password: ''